version: '2'

services:

  unifi:
    build: ./unifi
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - unifi:/usr/lib/unifi/data
      - unifi:/usr/lib/unifi/run
      - unifi:/usr/lib/unifi/log
      - www-data:/var/www

#  spotify:
#    build: ./balena-sound/spotify
#    restart: on-failure
#    network_mode: host
#    privileged: true
#    volumes:
#      - spotifycache:/var/cache/raspotify

volumes:

  unifi:
  www-data:
  spotifycache:

